### ISSUE TITLE
Deleting an asset with service records causes integrity error.

### ISSUE THREAD

**Issue by Judman** [RyGuy994/MATER#12]
I attempted to deleted the MATER asset with service records still intact and was thrown to an integrity error webpage. I imagine this is database related in order to prevent orphaned records that are tried to an existing asses.

<details><summary>Webpage error details included here</summary>
<p>

```

IntegrityError

sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) NOT NULL constraint failed: service.asset_id
[SQL: UPDATE service SET asset_id=? WHERE service.id = ?]
[parameters: [(None, 4), (None, 5)]]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
Traceback (most recent call last)

    File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1938, in _exec_single_context

    self.dialect.do_executemany(

    File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 919, in do_executemany

    cursor.executemany(statement, parameters)

    The above exception was the direct cause of the following exception:
    File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1478, in __call__

    return self.wsgi_app(environ, start_response)

    File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1458, in wsgi_app

    response = self.handle_exception(e) [Open an interactive python shell in this frame] 

    File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1455, in wsgi_app

    response = self.full_dispatch_request()

    File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 869, in full_dispatch_request

    rv = self.handle_user_exception(e)

    File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 867, in full_dispatch_request

    rv = self.dispatch_request()

    File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 852, in dispatch_request

    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)

    File "/app/app.py", line 158, in delete_asset

    db.session.commit() # commit to DB

    File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/scoping.py", line 598, in commit

    return self._proxied.commit()

    File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1969, in commit

    trans.commit(_to_root=True)

    File "<string>", line 2, in commit
    File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go

    ret_value = fn(self, *arg, **kw)

    File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1256, in commit

    self._prepare_impl()

    File "<string>", line 2, in _prepare_impl
    File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go

    ret_value = fn(self, *arg, **kw)

    File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1231, in _prepare_impl

    self.session.flush()

    File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 4312, in flush

    self._flush(objects)

    File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 4448, in _flush

    transaction.rollback(_capture_exception=True)

    File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__

    raise exc_value.with_traceback(exc_tb)

    File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 4408, in _flush

    flush_context.execute()

    File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute

    rec.execute(self)

    File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute

    util.preloaded.orm_persistence.save_obj(

    File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 85, in save_obj

    _emit_update_statements(

    File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 909, in _emit_update_statements

    c = connection.execute(

    File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1416, in execute

    return meth(

    File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 516, in _execute_on_connection

    return connection._execute_clauseelement(

    File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1639, in _execute_clauseelement

    ret = self._execute_context(

    File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1848, in _execute_context

    return self._exec_single_context(

    File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1988, in _exec_single_context

    self._handle_dbapi_exception(

    File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2343, in _handle_dbapi_exception

    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e

    File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1938, in _exec_single_context

    self.dialect.do_executemany(

    File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 919, in do_executemany

    cursor.executemany(statement, parameters)

    sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) NOT NULL constraint failed: service.asset_id
    [SQL: UPDATE service SET asset_id=? WHERE service.id = ?]
    [parameters: [(None, 4), (None, 5)]]
    (Background on this error at: https://sqlalche.me/e/20/gkpj)

The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.

To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.

You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:

    dump() shows all variables in the frame
    dump(obj) dumps all that's known about the object

Brought to you by DON'T PANIC, your friendly Werkzeug powered traceback interpreter.

``` 

</p>
</details> 

I did double check that this was related to additional records by making a new asset and immediately deleting  without any error. Then I created another test asset, added a service record then attempted to delete the asset and received the same Integrity Error.

Steps to replicate:
1. Create a new asset (testcar1).
2. Create a new service record (oil change) related to new asset (testcar1).
3. Attempt to delete new asset (testcar1).

I wish I knew more about programming to be able to contribute.

**Comment by RyGuy994** [comment]
This is perfect. I found where the air is reaching out. I need to delete the services before the asset!

**Comment by Judman** [comment]
Might I suggest, if an asset has services attached, a warning and confirmation before deleting the asset. Maybe something that warns you there are services then makes you type the name of the asset into a text box before deleting.

**Comment by RyGuy994** [comment]
Just asking. Is there a warning that comes up now? or maybe a second warning that says are you sure because this assets has services

**Comment by Judman** [comment]
Can confirm there is a warning now regardless of add on records. However, if deleting an asset is also going to delete service records that is a more severe action. To me that warrants a more deliberate deletion process.

**Comment by RyGuy994** [comment]
does a warning with "This Asset has Services attached to it" Please type "DELETE ASSET" in the box below and click submit?

**Comment by Judman** [comment]
I think that is a fine warning.

**Comment by RyGuy994** [comment]
I've changed it a little bit but I think I've settled on a blanket type "Delete asset" for all them
