### ISSUE TITLE
[BUG] When sqlite file is not present the database errors out.

### ISSUE THREAD

**Issue by RyGuy994** [RyGuy994/MATER#50]
Error below. Code doesn't create and check path.

mater2-web-1  | Traceback (most recent call last):
mater2-web-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 145, in __init__
mater2-web-1  |     self._dbapi_connection = engine.raw_connection()
mater2-web-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3293, in raw_connection
mater2-web-1  | Making all tables now!
mater2-web-1  |     return self.pool.connect()
mater2-web-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 452, in connect
mater2-web-1  |     return _ConnectionFairy._checkout(self)
mater2-web-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 1269, in _checkout
mater2-web-1  |     fairy = _ConnectionRecord.checkout(pool)
mater2-web-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 716, in checkout
mater2-web-1  |     rec = pool._do_get()
mater2-web-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 169, in _do_get
mater2-web-1  |     with util.safe_reraise():
mater2-web-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
mater2-web-1  |     raise exc_value.with_traceback(exc_tb)
mater2-web-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 167, in _do_get
mater2-web-1  |     return self._create_connection()
mater2-web-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 393, in _create_connection
mater2-web-1  |     return _ConnectionRecord(self)
mater2-web-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 678, in __init__
mater2-web-1  |     self.__connect()
mater2-web-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 902, in __connect
mater2-web-1  |     with util.safe_reraise():
mater2-web-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
mater2-web-1  |     raise exc_value.with_traceback(exc_tb)
mater2-web-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 898, in __connect
mater2-web-1  |     self.dbapi_connection = connection = pool._invoke_creator(self)
mater2-web-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 645, in connect
mater2-web-1  |     return dialect.connect(*cargs, **cparams)
mater2-web-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 616, in connect
mater2-web-1  |     return self.loaded_dbapi.connect(*cargs, **cparams)
mater2-web-1  | sqlite3.OperationalError: unable to open database file
mater2-web-1  |
mater2-web-1  | The above exception was the direct cause of the following exception:
mater2-web-1  |
mater2-web-1  | Traceback (most recent call last):
mater2-web-1  |   File "/app/app.py", line 15, in <module>
mater2-web-1  |     from blueprints.base import app
mater2-web-1  |   File "/app/blueprints/base.py", line 4, in <module>
mater2-web-1  |     from .configuration import app
mater2-web-1  |   File "/app/blueprints/configuration.py", line 60, in <module>
mater2-web-1  |     create_db_tables(app, db, 'sqlite')
mater2-web-1  |   File "/app/blueprints/configuration.py", line 23, in create_db_tables
mater2-web-1  |     db.create_all() # create all tables in database
mater2-web-1  |   File "/usr/local/lib/python3.10/site-packages/flask_sqlalchemy/extension.py", line 900, in create_all
mater2-web-1  |     self._call_for_binds(bind_key, "create_all")
mater2-web-1  |   File "/usr/local/lib/python3.10/site-packages/flask_sqlalchemy/extension.py", line 881, in _call_for_binds
mater2-web-1  |     getattr(metadata, op_name)(bind=engine)
mater2-web-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/sql/schema.py", line 5832, in create_all
mater2-web-1  |     bind._run_ddl_visitor(
mater2-web-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3243, in _run_ddl_visitor
mater2-web-1  |     with self.begin() as conn:
mater2-web-1  |   File "/usr/local/lib/python3.10/contextlib.py", line 135, in __enter__
mater2-web-1  |     return next(self.gen)
mater2-web-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3233, in begin
mater2-web-1  |     with self.connect() as conn:
mater2-web-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3269, in connect
mater2-web-1  |     return self._connection_cls(self)
mater2-web-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 147, in __init__
mater2-web-1  |     Connection._handle_dbapi_exception_noconnection(
mater2-web-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2431, in _handle_dbapi_exception_noconnection
mater2-web-1  |     raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
mater2-web-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 145, in __init__
mater2-web-1  |     self._dbapi_connection = engine.raw_connection()
mater2-web-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3293, in raw_connection
mater2-web-1  |     return self.pool.connect()
mater2-web-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 452, in connect
mater2-web-1  |     return _ConnectionFairy._checkout(self)
mater2-web-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 1269, in _checkout
mater2-web-1  |     fairy = _ConnectionRecord.checkout(pool)
mater2-web-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 716, in checkout
mater2-web-1  |     rec = pool._do_get()
mater2-web-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 169, in _do_get
mater2-web-1  |     with util.safe_reraise():
mater2-web-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
mater2-web-1  |     raise exc_value.with_traceback(exc_tb)
mater2-web-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 167, in _do_get
mater2-web-1  |     return self._create_connection()
mater2-web-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 393, in _create_connection
mater2-web-1  |     return _ConnectionRecord(self)
mater2-web-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 678, in __init__
mater2-web-1  |     self.__connect()
mater2-web-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 902, in __connect
mater2-web-1  |     with util.safe_reraise():
mater2-web-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
mater2-web-1  |     raise exc_value.with_traceback(exc_tb)
mater2-web-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 898, in __connect
mater2-web-1  |     self.dbapi_connection = connection = pool._invoke_creator(self)
mater2-web-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 645, in connect
mater2-web-1  |     return dialect.connect(*cargs, **cparams)
mater2-web-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 616, in connect
mater2-web-1  |     return self.loaded_dbapi.connect(*cargs, **cparams)
mater2-web-1  | sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
mater2-web-1  | (Background on this error at: https://sqlalche.me/e/20/e3q8)

**Comment by RyGuy994** [comment]
WIP
